### ISSUE TITLE
Duplicated line in momentumopt/srcpy/momentumopt/dynopt/PyDynamics.cpp

### ISSUE THREAD

**Issue by pFernbach** [machines-in-motion/kino_dynamic_opt#20]
https://github.com/machines-in-motion/kino_dynamic_opt/blob/0448e911d3b844b9e83f5c2399f82ffe956b8b03/momentumopt/srcpy/momentumopt/dynopt/PyDynamics.cpp#L36

**Comment by MaximilienNaveau** [comment]
A PR is always welcome^^
I may suggest not before: https://github.com/machines-in-motion/kino_dynamic_opt/pull/37

**Comment by jviereck** [comment]
Thanks for reporting this. I pushed a change removing the duplicate line.

**Comment by MaximilienNaveau** [comment]
The commit:
https://github.com/machines-in-motion/kino_dynamic_opt/commit/b133640cf5a5c291e83b03e72a48b1c831b3fd61
