### ISSUE TITLE
undefined reference to 'solver::.....

### ISSUE THREAD

**Issue by Akshay-9416** [machines-in-motion/kino_dynamic_opt#36]
Hello I am trying to 
$colcon build 
and I am facing the below issue
![image](https://user-images.githubusercontent.com/60077708/101769059-6aa86800-3b0c-11eb-8b5c-e9ca7d516069.png)
can someone please tell how to solve this issue.

Thank you.

**Comment by jviereck** [comment]
Thanks for your report. We are working on porting the library to ros2 right now - please see #34. Once the PR lands it will be possible to use colcon.
