### ISSUE TITLE
The Demo doesn't work

### ISSUE THREAD

**Issue by Kwach00** [machines-in-motion/kino_dynamic_opt#51]
Hello,

I encountered this issue while running the demo (the error occurs in the file 'kino_dyn_planner.py'):

```
from pymomentum import *
ImportError: Cannot overload existing non-function object "value" with a function of the same name
```

I saw that `pymomentum` includes a series of Python wrappers for C++ files, but I couldn't find any included function that would overload any existing non-function object. Has anyone else experienced a similar problem?

**Comment by wangdefo** [comment]
Hello, 
I meet the same problem, have you find any way that solved this problem?
 thank you

**Comment by Kwach00** [comment]
Hi!

Sorry for late response!

But yeah, I managed to workaround. In repository `pybind11` there is an implementation of error that forbids from using functions starting with one uderscore - `_` . You can find it here: [link](https://github.com/pybind/pybind11/blob/0a756c0bb2f7e7ac6cf4e2c4de26211409fadbe4/include/pybind11/pybind11.h#L536C71-L536C71).
So I just commented these three lines and it works just fine.

I hope it would help you, good luck!
